// Generated by CoffeeScript 1.6.3
(function() {
  describe("Recorder", function() {
    beforeEach(function() {
      var player;
      return player = new Recorder;
    });
    return it("should do something", function() {
      return expect(true).toBe­Tru­thy();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=recorderspec.map
*/
