// Generated by CoffeeScript 1.6.3
(function() {
  describe("Recorder", function() {
    beforeEach(function() {
      return this.recording = new Recording();
    });
    it("initializes", function() {
      expect(this.recording.errors.length).toEqual(0);
      return expect(this.recording.sampleRate).toEqual(44100);
    });
    it("sets and resets global variables (sorry...)", function() {
      window.__recording = -99;
      window.__leftchannel = -99;
      window.__rightchannel = -99;
      window.__recordingLength = -99;
      this.recording.setNastyGlobals();
      expect(window.__recording).toEqual(false);
      expect(window.__leftchannel).toEqual([]);
      expect(window.__rightchannel).toEqual([]);
      return expect(window.__recordingLength).toEqual(0);
    });
    return it('starts', function() {
      this.recording.start();
      waits(500);
      this.recording.stop();
      return expect(this.recording.blob.length).toBeGreaterThan(44);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=recorderspec.map
*/
