// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('#init').on('click', function(e) {
      e.preventDefault();
      window.recording1 = new Recording();
      $('#start').attr('href', '#');
      return $(this).text('');
    });
    $('#start').on('click', function(e) {
      e.preventDefault();
      window.recording1.start();
      $('#stop').attr('href', '#');
      return $(this).text('');
    });
    $('#stop').on('click', function(e) {
      e.preventDefault();
      window.recording1.stop();
      $('#dl').attr('href', '#');
      return $(this).text('');
    });
    return $('#dl').on('click', function(e) {
      e.preventDefault();
      window.recording1.download('wowSuperCool.wav');
      return $(this).text('');
    });
  });

}).call(this);

/*
//@ sourceMappingURL=demo.map
*/
